version: '2'

services:
  db:
    image: postgres:10-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: {{cookiecutter.project_slug}}
  redis:
    image: redis:3.2-alpine
    ports:
      - 6379:6379
